version: '3.7'

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8082:80
    depends_on:
      - backend
